# Các plugins từ Oh My Zsh
znap load ohmyzsh/ohmyzsh/plugins/alias-finder
znap load ohmyzsh/ohmyzsh/plugins/aliases
znap load ohmyzsh/ohmyzsh/plugins/ansible
znap load ohmyzsh/ohmyzsh/plugins/apache2-macports
znap load ohmyzsh/ohmyzsh/plugins/bundler
znap load ohmyzsh/ohmyzsh/plugins/branch
znap load ohmyzsh/ohmyzsh/plugins/cake
znap load ohmyzsh/ohmyzsh/plugins/cakephp3
znap load ohmyzsh/ohmyzsh/plugins/colored-man-pages
znap load ohmyzsh/ohmyzsh/plugins/common-aliases
znap load ohmyzsh/ohmyzsh/plugins/command-not-found
znap load ohmyzsh/ohmyzsh/plugins/composer
znap load ohmyzsh/ohmyzsh/plugins/copybuffer
znap load ohmyzsh/ohmyzsh/plugins/copyfile
znap load ohmyzsh/ohmyzsh/plugins/copypath
znap load ohmyzsh/ohmyzsh/plugins/cp
znap load ohmyzsh/ohmyzsh/plugins/debian
znap load ohmyzsh/ohmyzsh/plugins/dirhistory
znap load ohmyzsh/ohmyzsh/plugins/dirpersist
znap load ohmyzsh/ohmyzsh/plugins/dotenv
znap load ohmyzsh/ohmyzsh/plugins/eza
znap load ohmyzsh/ohmyzsh/plugins/extract
znap load ohmyzsh/ohmyzsh/plugins/fasd
znap load ohmyzsh/ohmyzsh/plugins/fastfile
znap load ohmyzsh/ohmyzsh/plugins/fzf
znap load ohmyzsh/ohmyzsh/plugins/fzf-tab
znap load ohmyzsh/ohmyzsh/plugins/fnm
znap load ohmyzsh/ohmyzsh/plugins/frontend-search
znap load ohmyzsh/ohmyzsh/plugins/gcloud
znap load ohmyzsh/ohmyzsh/plugins/git
znap load ohmyzsh/ohmyzsh/plugins/gitfast
znap load ohmyzsh/ohmyzsh/plugins/gitignore
znap load ohmyzsh/ohmyzsh/plugins/github
znap load ohmyzsh/ohmyzsh/plugins/git-prompt
znap load ohmyzsh/ohmyzsh/plugins/globalias
znap load ohmyzsh/ohmyzsh/plugins/gradle
znap load ohmyzsh/ohmyzsh/plugins/httpie
znap load ohmyzsh/ohmyzsh/plugins/jsontools
znap load ohmyzsh/ohmyzsh/plugins/last-working-dir
znap load ohmyzsh/ohmyzsh/plugins/man
znap load ohmyzsh/ohmyzsh/plugins/nmap
znap load ohmyzsh/ohmyzsh/plugins/npm
znap load ohmyzsh/ohmyzsh/plugins/nvm
znap load ohmyzsh/ohmyzsh/plugins/pip
znap load ohmyzsh/ohmyzsh/plugins/pipenv
znap load ohmyzsh/ohmyzsh/plugins/python
znap load ohmyzsh/ohmyzsh/plugins/rake
znap load ohmyzsh/ohmyzsh/plugins/rbenv
znap load ohmyzsh/ohmyzsh/plugins/rsync
znap load ohmyzsh/ohmyzsh/plugins/ruby
znap load ohmyzsh/ohmyzsh/plugins/sdk
znap load ohmyzsh/ohmyzsh/plugins/ssh
znap load ohmyzsh/ohmyzsh/plugins/sudo
znap load ohmyzsh/ohmyzsh/plugins/systemadmin
znap load ohmyzsh/ohmyzsh/plugins/systemd
znap load ohmyzsh/ohmyzsh/plugins/supervisor
znap load ohmyzsh/ohmyzsh/plugins/toolbox
znap load ohmyzsh/ohmyzsh/plugins/tmux
znap load ohmyzsh/ohmyzsh/plugins/universalarchive
znap load ohmyzsh/ohmyzsh/plugins/ufw
znap load ohmyzsh/ohmyzsh/plugins/ubuntu
znap load ohmyzsh/ohmyzsh/plugins/themes
znap load ohmyzsh/ohmyzsh/plugins/transfer
znap load ohmyzsh/ohmyzsh/plugins/textmate
znap load ohmyzsh/ohmyzsh/plugins/vi-mode
znap load ohmyzsh/ohmyzsh/plugins/web-search
znap load ohmyzsh/ohmyzsh/plugins/yum
znap load ohmyzsh/ohmyzsh/plugins/z
znap load ohmyzsh/ohmyzsh/plugins/zsh-autosuggestions
znap load ohmyzsh/ohmyzsh/plugins/zsh-interactive-cd
znap load ohmyzsh/ohmyzsh/plugins/zsh-completions
znap load ohmyzsh/ohmyzsh/plugins/argocd
znap load ohmyzsh/ohmyzsh/plugins/zsh-navigation-tools
znap load ohmyzsh/ohmyzsh/plugins/azure
znap load ohmyzsh/ohmyzsh/plugins/1password
znap load ohmyzsh/ohmyzsh/plugins/term_tab
znap load ohmyzsh/ohmyzsh/plugins/tmux-cssh
znap load ohmyzsh/ohmyzsh/plugins/tmuxinator
znap load ohmyzsh/ohmyzsh/plugins/git-auto-fetch
znap load ohmyzsh/ohmyzsh/plugins/git-commit
znap load ohmyzsh/ohmyzsh/plugins/git-extras
znap load ohmyzsh/ohmyzsh/plugins/magic-enter
znap load ohmyzsh/ohmyzsh/plugins/archlinux
znap load ohmyzsh/ohmyzsh/plugins/colorize
znap load ohmyzsh/ohmyzsh/plugins/compleat
znap load ohmyzsh/ohmyzsh/plugins/history-substring-search
znap load ohmyzsh/ohmyzsh/plugins/history
znap load ohmyzsh/ohmyzsh/plugins/emacs
znap load ohmyzsh/ohmyzsh/plugins/fancy-ctrl-z
znap load ohmyzsh/ohmyzsh/plugins/F-Sy-H
znap load ohmyzsh/ohmyzsh/plugins/git-lfs
znap load ohmyzsh/ohmyzsh/plugins/gnu-utils
znap load ohmyzsh/ohmyzsh/plugins/heroku-alias
znap load ohmyzsh/ohmyzsh/plugins/lighthouse
znap load ohmyzsh/ohmyzsh/plugins/localstack
znap load ohmyzsh/ohmyzsh/plugins/lpass
znap load ohmyzsh/ohmyzsh/plugins/multipass
znap load ohmyzsh/ohmyzsh/plugins/please
znap load ohmyzsh/ohmyzsh/plugins/profiles
znap load ohmyzsh/ohmyzsh/plugins/rails
znap load ohmyzsh/ohmyzsh/plugins/urltools
znap load ohmyzsh/ohmyzsh/plugins/terminitor
znap load ohmyzsh/ohmyzsh/plugins/autopep8
znap load ohmyzsh/ohmyzsh/plugins/aws
znap load ohmyzsh/ohmyzsh/plugins/colemak
znap load ohmyzsh/ohmyzsh/plugins/git-escape-magic
znap load ohmyzsh/ohmyzsh/plugins/operator-sdk
znap load ohmyzsh/ohmyzsh/plugins/snap
znap load ohmyzsh/ohmyzsh/plugins/vim-interaction
znap load ohmyzsh/ohmyzsh/plugins/alias-maker
znap load ohmyzsh/ohmyzsh/plugins/zsh-bat
znap load ohmyzsh/ohmyzsh/plugins/copytext
