github.com:
    users:
        boybh:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: boybh
