github.com:
    users:
        boybh:
            oauth_token: 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
            git_protocol: https
    git_protocol: ssh
    user: boybh
    oauth_token: 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
