github.com:
    users:
        boybh:
            oauth_token: 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
    git_protocol: ssh
    user: boybh
    oauth_token: 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
