github.com:
    users:
        boybh:
            oauth_token: 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
    git_protocol: ssh
    user: boybh
    oauth_token: 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
