# File: aliases.ps1

# Các alias từ file đã cung cấp
Set-Alias foreach ForEach-Object
Set-Alias % ForEach-Object
Set-Alias where Where-Object
Set-Alias ? Where-Object
Set-Alias clc Clear-Content
Set-Alias cli Clear-Item
Set-Alias clp Clear-ItemProperty
Set-Alias clv Clear-Variable
Set-Alias cpi Copy-Item
Set-Alias cvpa Convert-Path
Set-Alias dbp Disable-PSBreakpoint
Set-Alias ebp Enable-PSBreakpoint
Set-Alias epal Export-Alias
Set-Alias epcsv Export-Csv
Set-Alias fl Format-List
Set-Alias ft Format-Table
Set-Alias fw Format-Wide
Set-Alias gal Get-Alias
Set-Alias gbp Get-PSBreakpoint
Set-Alias gc Get-Content
Set-Alias gci Get-ChildItem
Set-Alias gcm Get-Command
Set-Alias gdr Get-PSDrive
Set-Alias gcs Get-PSCallStack
Set-Alias ghy Get-History
Set-Alias gi Get-Item
Set-Alias gl Get-Location
Set-Alias gm Get-Member
Set-Alias gmo Get-Module
Set-Alias gp Get-ItemProperty
Set-Alias gpv Get-ItemPropertyValue
Set-Alias gps Get-Process
Set-Alias group Group-Object
Set-Alias gu Get-Unique
Set-Alias gv Get-Variable
Set-Alias iex Invoke-Expression
Set-Alias ihy Invoke-History
Set-Alias ii Invoke-Item
Set-Alias ipmo Import-Module
Set-Alias ipal Import-Alias
Set-Alias ipcsv Import-Csv
Set-Alias measure Measure-Object
Set-Alias mi Move-Item
Set-Alias mp Move-ItemProperty
Set-Alias nal New-Alias
Set-Alias ndr New-PSDrive
Set-Alias ni New-Item
Set-Alias nv New-Variable
Set-Alias nmo New-Module
Set-Alias oh Out-Host
Set-Alias rbp Remove-PSBreakpoint
Set-Alias rdr Remove-PSDrive
Set-Alias ri Remove-Item
Set-Alias rni Rename-Item
Set-Alias rnp Rename-ItemProperty
Set-Alias rp Remove-ItemProperty
Set-Alias rmo Remove-Module
Set-Alias rv Remove-Variable
Set-Alias gerr Get-Error
Set-Alias rvpa Resolve-Path
Set-Alias sal Set-Alias
Set-Alias sbp Set-PSBreakpoint
Set-Alias select Select-Object
Set-Alias si Set-Item
Set-Alias sl Set-Location
Set-Alias sp Set-ItemProperty
Set-Alias saps Start-Process
Set-Alias spps Stop-Process
Set-Alias sv Set-Variable
Set-Alias irm Invoke-RestMethod
Set-Alias iwr Invoke-WebRequest
Set-Alias ac Add-Content
Set-Alias clear Clear-Host
Set-Alias compare Compare-Object
Set-Alias cpp Copy-ItemProperty
Set-Alias diff Compare-Object
Set-Alias gsv Get-Service
Set-Alias sleep Start-Sleep
Set-Alias sort Sort-Object
Set-Alias start Start-Process
Set-Alias sasv Start-Service
Set-Alias spsv Stop-Service
Set-Alias tee Tee-Object
Set-Alias write Write-Output
Set-Alias cat Get-Content
Set-Alias cp Copy-Item
Set-Alias ls Get-ChildItem
Set-Alias man help
Set-Alias mount New-PSDrive
Set-Alias mv Move-Item
Set-Alias ps Get-Process
Set-Alias rm Remove-Item
Set-Alias rmdir Remove-Item
Set-Alias cnsn Connect-PSSession
Set-Alias dnsn Disconnect-PSSession
Set-Alias ogv Out-GridView
Set-Alias shcm Show-Command
Set-Alias cd Set-Location
Set-Alias dir Get-ChildItem
Set-Alias echo Write-Output
Set-Alias fc Format-Custom
Set-Alias kill Stop-Process
Set-Alias pwd Get-Location
Set-Alias type Get-Content
Set-Alias h Get-History
Set-Alias history Get-History
Set-Alias md mkdir
Set-Alias popd Pop-Location
Set-Alias pushd Push-Location
Set-Alias r Invoke-History
Set-Alias cls Clear-Host
Set-Alias chdir Set-Location
Set-Alias copy Copy-Item
Set-Alias del Remove-Item
Set-Alias erase Remove-Item
Set-Alias move Move-Item
Set-Alias rd Remove-Item
Set-Alias ren Rename-Item
Set-Alias set Set-Variable
Set-Alias icm Invoke-Command
Set-Alias clhy Clear-History
Set-Alias gjb Get-Job
Set-Alias rcjb Receive-Job
Set-Alias rjb Remove-Job
Set-Alias sajb Start-Job
Set-Alias spjb Stop-Job
Set-Alias wjb Wait-Job
Set-Alias nsn New-PSSession
Set-Alias gsn Get-PSSession
Set-Alias rsn Remove-PSSession
Set-Alias etsn Enter-PSSession
Set-Alias rcsn Receive-PSSession
Set-Alias exsn Exit-PSSession
Set-Alias sls Select-String
Set-Alias gcb Get-Clipboard
Set-Alias gin Get-ComputerInfo
Set-Alias gtz Get-TimeZone
Set-Alias scb Set-Clipboard
Set-Alias stz Set-TimeZone
Set-Alias fhx Format-Hex
Set-Alias CFS ConvertFrom-String
Set-Alias nssm "E:\dnsproxy\nssm.exe"

