github.com:
    users:
        boybh:
            oauth_token: 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
    git_protocol: https
    user: boybh
    oauth_token: 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
