gh extension install yusukebe/gh-markdown-preview
gh extension install dlvhdr/gh-dash
gh extension install yuler/gh-download
gh extension install Link-/gh-token
gh extension install github/gh-net
gh extension install mislav/gh-branch
gh extension install github/gh-actions-importer
gh extension install gabe565/gh-profile
gh extension install gennaro-tedesco/gh-f
